In [44]:
import pandas as pd
import numpy as np
from numpy.linalg import inv

# **Q1. Pandas version**

What's the version of Pandas that you installed?

You can get the version information using the __version__ field:

In [3]:
pd.__version__

'2.2.2'

# **Getting the data**

For this homework, we'll use the Car Fuel Efficiency dataset. Download it from here.

You can do it with wget:

In [5]:
!wget https://raw.githubusercontent.com/alexeygrigorev/datasets/master/car_fuel_efficiency.csv

--2025-09-21 10:43:39--  https://raw.githubusercontent.com/alexeygrigorev/datasets/master/car_fuel_efficiency.csv
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.108.133, 185.199.109.133, 185.199.110.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.108.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 874188 (854K) [text/plain]
Saving to: ‘car_fuel_efficiency.csv’

car_fuel_efficiency 100%[===================>] 853.70K  --.-KB/s    in 0.04s   

2025-09-21 10:43:40 (21.3 MB/s) - ‘car_fuel_efficiency.csv’ saved [874188/874188]



# **Loading the dataset as a DataFrame**

In [6]:
df_fuel = pd.read_csv('car_fuel_efficiency.csv')
df_fuel.head()

engine_displacement  num_cylinders  horsepower  vehicle_weight  \
0                  170            3.0       159.0     3413.433759   
1                  130            5.0        97.0     3149.664934   
2                  170            NaN        78.0     3079.038997   
3                  220            4.0         NaN     2542.392402   
4                  210            1.0       140.0     3460.870990   

   acceleration  model_year  origin fuel_type         drivetrain  num_doors  \
0          17.7        2003  Europe  Gasoline    All-wheel drive        0.0   
1          17.8        2007     USA  Gasoline  Front-wheel drive        0.0   
2          15.1        2018  Europe  Gasoline  Front-wheel drive        0.0   
3          20.2        2009     USA    Diesel    All-wheel drive        2.0   
4          14.4        2009  Europe  Gasoline    All-wheel drive        2.0   

   fuel_efficiency_mpg  
0            13.231729  
1            13.688217  
2            14.246341  
3            16.912736  
4            12.488369

# **Q2. Records count**

How many records are in the dataset?

In [7]:
print(f"The dataset contains {df_fuel.shape[0]} records and {df_fuel.shape[1]} features")

The dataset contains 9704 records and 11 features


# **Q3. Fuel types**

How many fuel types are presented in the dataset?

In [10]:
print(f"The data set contains {len(df_fuel['fuel_type'].unique())} fuel types")

The data set contains 2 fuel types


# **Q4. Missing values**

How many columns in the dataset have missing values?

In [13]:
no_missing_values = df_fuel.isna().sum()
no_missing_values[no_missing_values > 0]

num_cylinders    482
horsepower       708
acceleration     930
num_doors        502
dtype: int64

In [14]:
print(f"The dataset has {len(no_missing_values[no_missing_values > 0])} columns with missing values")

The dataset has 4 columns with missing values


# **Q5. Max fuel efficiency**

What's the maximum fuel efficiency of cars from Asia?

In [15]:
df_fuel.head()

engine_displacement  num_cylinders  horsepower  vehicle_weight  \
0                  170            3.0       159.0     3413.433759   
1                  130            5.0        97.0     3149.664934   
2                  170            NaN        78.0     3079.038997   
3                  220            4.0         NaN     2542.392402   
4                  210            1.0       140.0     3460.870990   

   acceleration  model_year  origin fuel_type         drivetrain  num_doors  \
0          17.7        2003  Europe  Gasoline    All-wheel drive        0.0   
1          17.8        2007     USA  Gasoline  Front-wheel drive        0.0   
2          15.1        2018  Europe  Gasoline  Front-wheel drive        0.0   
3          20.2        2009     USA    Diesel    All-wheel drive        2.0   
4          14.4        2009  Europe  Gasoline    All-wheel drive        2.0   

   fuel_efficiency_mpg  
0            13.231729  
1            13.688217  
2            14.246341  
3            16.912736  
4            12.488369

In [24]:
print(f"The maximum fuel efficiency is {round(df_fuel[df_fuel['origin'] == 'Asia']['fuel_efficiency_mpg'].max(), 2)}")

The maximum fuel efficiency is 23.76


# **Q6. Median value of horsepower**

1. Find the median value of horsepower column in the dataset.
2. Next, calculate the most frequent value of the same horsepower column.
3. Use fillna method to fill the missing values in horsepower column with the most frequent value from the previous step.
4. Now, calculate the median value of horsepower once again.

In [29]:
# 1
print(f"The median value of horsepower is {round(df_fuel['horsepower'].median(), 2)}")

# 2
horsepower_mode = df_fuel['horsepower'].mode()[0]
print(f"The most frequent value of horsepower is {horsepower_mode}")

#3
new_horsepower_value = df_fuel['horsepower'].fillna(horsepower_mode)

#4
print(f"The median value of horsepower after filling the missing values is {round(new_horsepower_value.median(), 2)}")

The median value of horsepower is 149.0
The most frequent value of horsepower is 152.0
The median value of horsepower after filling the missing values is 152.0


# **Q7. Sum of weights**

1. Select all the cars from Asia
2. Select only columns vehicle_weight and model_year
3. Select the first 7 values
4. Get the underlying NumPy array. Let's call it X.
5. Compute matrix-matrix multiplication between the transpose of X and X. To get the transpose, use X.T. Let's call the result XTX.
6. Invert XTX.
7. Create an array y with values [1100, 1300, 800, 900, 1000, 1100, 1200].
8. Multiply the inverse of XTX with the transpose of X, and then multiply the result by y. Call the result w.
9. What's the sum of all the elements of the result?


In [33]:
#1
df_fuel[df_fuel['origin'] == 'Asia']

engine_displacement  num_cylinders  horsepower  vehicle_weight  \
8                     250            1.0       174.0     2714.219310   
12                    320            5.0       145.0     2783.868974   
14                    200            6.0       160.0     3582.687368   
20                    150            3.0       197.0     2231.808142   
21                    160            4.0       133.0     2659.431451   
...                   ...            ...         ...             ...   
9688                  260            4.0         NaN     3948.404625   
9692                  180            3.0       188.0     3680.341381   
9693                  280            2.0       148.0     2545.070139   
9698                  180            1.0       131.0     3107.427820   
9703                  270            3.0       140.0     2908.043477   

      acceleration  model_year origin fuel_type         drivetrain  num_doors  \
8             10.3        2016   Asia    Diesel  Front-wheel drive       -1.0   
12            15.1        2010   Asia    Diesel    All-wheel drive        1.0   
14            14.9        2007   Asia    Diesel    All-wheel drive        0.0   
20            18.7        2011   Asia  Gasoline  Front-wheel drive        1.0   
21             NaN        2016   Asia  Gasoline  Front-wheel drive       -1.0   
...            ...         ...    ...       ...                ...        ...   
9688          15.5        2018   Asia    Diesel    All-wheel drive       -1.0   
9692          18.0        2016   Asia  Gasoline  Front-wheel drive        1.0   
9693          15.6        2012   Asia    Diesel    All-wheel drive        0.0   
9698          13.2        2005   Asia  Gasoline  Front-wheel drive       -2.0   
9703          14.7        2005   Asia    Diesel    All-wheel drive       -1.0   

      fuel_efficiency_mpg  
8               16.823554  
12              16.175820  
14              11.871091  
20              18.889083  
21              16.077730  
...                   ...  
9688            11.054830  
9692            11.711653  
9693            17.202782  
9698            13.933716  
9703            14.884467  

[3247 rows x 11 columns]

In [35]:
#2
selected_columns = df_fuel.loc[df_fuel['origin'] == 'Asia', ['vehicle_weight', 'model_year']]

In [36]:
#3
selected_columns.head(7)

vehicle_weight  model_year
8      2714.219310        2016
12     2783.868974        2010
14     3582.687368        2007
20     2231.808142        2011
21     2659.431451        2016
34     2844.227534        2014
38     3761.994038        2019

In [38]:
#4
X = selected_columns.head(7).to_numpy()
X

array([[2714.21930965, 2016.        ],
       [2783.86897424, 2010.        ],
       [3582.68736772, 2007.        ],
       [2231.8081416 , 2011.        ],
       [2659.43145076, 2016.        ],
       [2844.22753389, 2014.        ],
       [3761.99403819, 2019.        ]])

In [39]:
#5
X.T

array([[2714.21930965, 2783.86897424, 3582.68736772, 2231.8081416 ,
        2659.43145076, 2844.22753389, 3761.99403819],
       [2016.        , 2010.        , 2007.        , 2011.        ,
        2016.        , 2014.        , 2019.        ]])

In [42]:
XTX = np.matmul(X.T, X)
XTX

array([[62248334.33150762, 41431216.5073268 ],
       [41431216.5073268 , 28373339.        ]])

In [46]:
#6
XTX_inv = inv(XTX)
XTX_inv

array([[ 5.71497081e-07, -8.34509443e-07],
       [-8.34509443e-07,  1.25380877e-06]])

In [47]:
#7
y = np.array([1100, 1300, 800, 900, 1000, 1100, 1200])
y

array([1100, 1300,  800,  900, 1000, 1100, 1200])

In [48]:
#8
w = np.matmul(XTX_inv, X.T) * y
w

array([[-0.14432288, -0.11230828,  0.29810794, -0.36245398, -0.16251372,
        -0.06075771,  0.55811286],
       [ 0.28890053,  0.2560879 , -0.37871378,  0.59305003,  0.30835783,
         0.16679975, -0.72957556]])

In [50]:
#9
print(f"the sum of all the element of the result is {w.sum()}")

the sum of all the element of the result is 0.5187709081074016
